### ISSUE TITLE
紧急处理的所有事情

### ISSUE THREAD

**Issue by ljm12914** [fyscu/foc_fe#1]
- [x] 注销（前端要做）
- [x] 手机号换绑
- [x] AI
- [x] 历史记录页按钮
- [x] 新建工单允许不上传图片
- [x] 显示报修同学 QQ 号
- [x] onLaunch时自动登录

**Comment by nanguaguag** [comment]
还有，历史记录页的报修按钮点了没用

**Comment by dongguaguaguagua** [comment]
报修上传一张照片应该是后端的限制
