### ISSUE TITLE
要求技术员在完成工单时提交照片

### ISSUE THREAD

**Issue by ljm12914** [fyscu/foc_fe#17]
如题
至少提交一张照片，才能在技术员端完成订单
在提交页说明，这个操作是为了留档取证，保护技术员免遭奇怪问题和奇怪人的影响

**Comment by wjlfish** [comment]
工单数据库已支持传入`complete_image_url`字段，用以处理完成工单时的图片存储。应调用标准图片上传接口后将返回的url填入此项。目前此项不是必须项，后续可根据需求设置为必须项。

**Comment by wjlfish** [comment]
1.1.2已正式上线
