### ISSUE TITLE
华西技术员榜与望江技术员榜合并

### ISSUE THREAD

**Issue by zimya** [fyscu/foc_fe#21]
华西实在凑不出一个榜。。。

**Comment by wjlfish** [comment]
已增加磨子桥榜
查询v1/status/getLaomo时请附带campus参数，参数列表如下
磨子桥aka：m
望江aka：w
江安aka：j
华西aka：h
建议使用字母缩写

**Comment by wjlfish** [comment]
（加成磨子桥榜了以后发现前三里还是没有华西的朋友。。。）
