### ISSUE TITLE
控制暂停接单的单独字段

### ISSUE THREAD

**Issue by ljm12914** [fyscu/foc_fe#5]

**Comment by wjlfish** [comment]
已经添加 `wants` 字段于主用户表中，setUser和getUser接口已经可以获取到此值
此值最大为100（极想接单），最小为0（完全不想接单），默认为100
此值将会在未来被视为权重进入派单计算

**Comment by ljm12914** [comment]
> 已经添加 `wants` 字段于主用户表中，setUser和getUser接口已经可以获取到此值 此值最大为100（极想接单），最小为0（完全不想接单），默认为100 此值将会在未来被视为权重进入派单计算

默认应设为中间值（如50），否则无法实现有部分技术员比其他技术员更想接单的功能。不需要使用连续数字，希望调整为有极的参数类型（或仅支持某些数字），以方便显示和前端开发。

**Comment by wjlfish** [comment]
好，那不如用abcde五个等第来表示。用纯数字有些担心会触发php的什么奇奇怪怪的bug，干脆用字母来表示。
a: 0%
b: 25%
c: 50%
d: 75%
e: 100%
