### ISSUE TITLE
技术员转让工单

### ISSUE THREAD

**Issue by ljm12914** [fyscu/foc_fe#8]
- [x] 二维码转单
- [ ] 验证码转单

两个技术员必须均同意
1. 技术员A点击转让工单，通过技术员B提供的自己的技术员号（即ID）找到，可以补充说明，提交
2. 技术员B看到转让请求，点击同意或拒绝
//

A技术员在工单页面点击按钮进入转单页面，输入B技术员的技术员号，提交后回到首页，该工单置灰，无法点进查看或操作，并显示“转单确认中”，同时通过微信提醒或短信通知技术员B，技术员B在工单处看到类似工单的项目，不可点进，显示工单的标题和缩略图，并提供“接受”“拒绝”两个按钮，点击接受后，加载为正常工单，点击拒绝后，该项目消失。A技术员（微信或短信）收到接受或拒绝通知，若拒绝则A技术员可以继续查看并操作工单。若接受则A技术员工单消失。

**Comment by zimya** [comment]
先实现扫码转单功能（实现起来比较简单）：

1. 技术员A在工单页保存二维码
2. 技术员将二维码转发给技术员B
3. 技术员B点击首页「扫码接单」，从相册中选择二维码
4. 工单直接显示在技术员B首页

**Comment by ljm12914** [comment]
- [ ] 二维码转单
- [x] 验证码转单

**Comment by wjlfish** [comment]
验证码功能以添加，可以通过`v1/status/getTicket`接口返回的transcode项来获取验证码；同时，`v1/ticket/give`接口支持通过验证码+工单id的方式进行工单转移了，用法：
- 一、工单验证阶段：
    1. 传入`order_id`与`tvcode`，二者匹配则可分配
    2. 传入`order_id`与`order_hash`，二者匹配则可分配
    （上述1，2满足一种条件即可通过转移/分配验证，若同时传入`tvcode`和`order_hash`，则优先处理`order_hash`）
- 二、转移/分配阶段
    - 传入`tid`（非必须）
    - 若传入了`tid`且发起该请求的用户身份为管理员，则将该工单强制转移/分配给该技术员
    - 若未传入`tid`，则默认将订单转给发起请求的技术员。
（即：未传入tid时，发起请求的用户必须为技术员本人）

**Comment by wjlfish** [comment]
已完成并等待前端适配

**Comment by zimya** [comment]
前端已适配。
